/*
 * Metabase
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package metabase

type FieldSettings struct {
	DateAbbreviate   bool   `json:"date_abbreviate,omitempty"`
	DateSeparator    string `json:"date_separator,omitempty"`
	DateStyle        string `json:"date_style,omitempty"`
	TimeEnabled      string `json:"time_enabled,omitempty"`
	TimeStyle        string `json:"time_style,omitempty"`
	Currency         string `json:"currency,omitempty"`
	CurrencyInHeader bool   `json:"currency_in_header,omitempty"`
	CurrencyStyle    string `json:"currency_style,omitempty"`
	Decimals         int32  `json:"decimals,omitempty"`
	NumberSeparators string `json:"number_separators,omitempty"`
	Prefix           string `json:"prefix,omitempty"`
	Scale            int32  `json:"scale,omitempty"`
	ShowMiniBar      bool   `json:"show_mini_bar,omitempty"`
	Suffix           string `json:"suffix,omitempty"`
	LinkText         string `json:"link_text,omitempty"`
	ViewAs           string `json:"view_as,omitempty"`
}
