/*
 * Metabase
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package metabase

type TableMetadata struct {
	Id                   int64   `json:"id"`
	Name                 string  `json:"name,omitempty"`
	DisplayName          string  `json:"display_name,omitempty"`
	EntityName           string  `json:"entity_name,omitempty"`
	EntityType           string  `json:"entity_type,omitempty"`
	VisibilityType       string  `json:"visibility_type,omitempty"`
	Description          string  `json:"description,omitempty"`
	Caveats              string  `json:"caveats,omitempty"`
	PointsOfInterest     string  `json:"points_of_interest,omitempty"`
	ShowInGettingStarted bool    `json:"show_in_getting_started,omitempty"`
	DbId                 int64   `json:"db_id,omitempty"`
	Fields               []Field `json:"fields,omitempty"`
}
