/*
 * Metabase
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package metabase

type Field struct {
	Id              int64  `json:"id"`
	TableId         int64  `json:"table_id,omitempty"`
	Name            string `json:"name,omitempty"`
	DisplayName     string `json:"display_name,omitempty"`
	VisibilityType  string `json:"visibility_type,omitempty"`
	Description     string `json:"description,omitempty"`
	DatabaseType    string `json:"database_type,omitempty"`
	SpecialType     string `json:"special_type,omitempty"`
	Settings        string `json:"settings,omitempty"`
	FkTargetFieldId int64  `json:"fk_target_field_id,omitempty"`
	Active          bool   `json:"active,omitempty"`
	ParentId        int64  `json:"parent_id,omitempty"`
	Position        int64  `json:"position,omitempty"`
	Target          string `json:"target,omitempty"`
	PreviewDisplay  bool   `json:"preview_display,omitempty"`
}
